
<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=963514153780722";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<!--<div class="row top-navbar" style="background-color: #ffffff;">
    <div class="container">
        <div class="navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Danh mục</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="menu-item dropdown-toggle" data-toggle="dropdown">Mỹ phẩm&nbsp;<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Mỹ phẩm 1</a></li>
                                <li><a href="#">Mỹ phẩm 2</a></li>
                                <li><a href="#">Mỹ phẩm 3</a></li>
                                <li><a href="#">Mỹ phẩm 4</a></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mỹ phẩm 5<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Mỹ phẩm 5.1</a></li>
                                        <li>
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mỹ phẩm 5.2<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mỹ phẩm 5.2.1 <b class="caret"></b></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="#">Mỹ phẩm 5.2.1.1</a></li>
                                                        <li><a href="#">Mỹ phẩm 5.2.1.2</a></li>
                                                        <li><a href="#">Mỹ phẩm 5.2.1.3</a></li>
                                                        <li><a href="#">Mỹ phẩm 5.2.1.4</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="menu-item dropdown-toggle" data-toggle="dropdown">Thực phẩm chức năng&nbsp;<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Thực phẩm chức năng 1</a></li>
                                <li><a href="#">Thực phẩm chức năng 2</a></li>
                                <li><a href="#">Thực phẩm chức năng 3</a></li>
                                <li><a href="#">Thực phẩm chức năng 4</a></li>
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Thực phẩm chức năng 5<b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Thực phẩm chức năng 5.1</a></li>
                                        <li>
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Thực phẩm chức năng 5.2<b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Thực phẩm chức năng 5.2.1 <b class="caret"></b></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="#">Thực phẩm chức năng 5.2.1.1</a></li>
                                                        <li><a href="#">Thực phẩm chức năng 5.2.1.2</a></li>
                                                        <li><a href="#">Thực phẩm chức năng 5.2.1.3</a></li>
                                                        <li><a href="#">Thực phẩm chức năng 5.2.1.4</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li><a class="menu-item" href="#">Blog</a></li>
                        <li><a class="menu-item" href="lam-dep-va-suc-khoe.html">Làm đẹp và Sức khỏe</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>-->


<div class="row">
    <div class="col-xs-12">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="<?php echo $block->getViewFileUrl('images/slider/636256530627585970.jpg'); ?>" alt="Chania">
                </div>

                <div class="item">
                    <img src="<?php echo $block->getViewFileUrl('images/slider/636256530627635803.jpg'); ?>" alt="Chania">
                </div>

                <div class="item">
                    <img src="<?php echo $block->getViewFileUrl('images/slider/636256530627585970.jpg'); ?>" alt="Chania">
                </div>

                <div class="item">
                    <img src="<?php echo $block->getViewFileUrl('images/slider/636256530627635803.jpg'); ?>" alt="Chania">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="container">
        <div class="col-xs-12 prod-group-items">
            <div class="col-xs-12 prod-group-title">
                <a href="danh-muc-san-pham.html">
                    <div class="prod-group-name pull-left">
                        COMBO KHUYẾN MẠI
                    </div>
                    <div class="prod-group-more pull-right">
                        XEM TẤT CẢ &nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 prod-group-list">
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-1.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-1.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-0.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-0.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="col-xs-12 prod-group-items">
            <div class="col-xs-12 prod-group-title">
                <a href="danh-muc-san-pham.html">
                    <div class="prod-group-name pull-left">
                        SẢN PHẨM ĐANG CÓ
                    </div>
                    <div class="prod-group-more pull-right">
                        XEM TẤT CẢ &nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 prod-group-list">
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-0.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-0.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-0.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-12 prod-item">
                    <div class="col-xs-12 prod-border">
                        <div class="promotion">
                            -50%
                        </div>
                        <div class="text-center btn-group">
                            <a href="gio-hang.html" class="btn btn-success btn-muangay">Mua ngay</a>
                            <button type="button" class="btn btn-danger btn-muangay">Giỏ hàng</button>
                        </div>
                        <a href="chi-tiet-san-pham.html">
                            <div class="image">
                                <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-0.png'); ?>" />
                            </div>
                            <div class="desc">
                                Bộ 2 thực phẩm bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da bảo vệ sức khỏe ngăn ngừa lão hóa sáng da
                            </div>
                            <div class="col-xs-12 price">
                                <div class="old-price pull-left">120.000 đ</div>
                                <div class="new-price pull-right">90.000 đ</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="container">
        <div class="col-xs-12 prod-group-items">
            <div class="col-xs-12 prod-group-title">
                <a href="danh-muc-san-pham.html">
                    <div class="prod-group-name pull-left">
                        ĐỐI TÁC
                    </div>
                    <!--<div class="prod-group-more pull-right">
                        XEM TẤT CẢ &nbsp;&nbsp;<i class="fa fa-caret-right" aria-hidden="true"></i>
                    </div>-->
                </a>
            </div>
            <div class="col-xs-12 prod-group-list">
                <div class="owl-carousel owl-theme">
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                    <div class="item">
                        <img src="<?php echo $block->getViewFileUrl('images/default-image.jpg'); ?>" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
