<footer>
    <div class="row row-connection">
        <div class="container">
            <div>
                <div class="col-md-2 col-sm-4 col-xs-6 connection-item">
                    <div class="col-xs-12 item">
                        <i class="fa fa-facebook-square" aria-hidden="true"></i>
                        <span>FACEBOOK</span>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 connection-item">
                    <div class="col-xs-12 item">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                        <span>INSTAGRAM</span>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 connection-item">
                    <div class="col-xs-12 item">
                        <i class="fa fa-twitter-square" aria-hidden="true"></i>
                        <span>TWITTER</span>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 connection-item">
                    <div class="col-xs-12 item">
                        <i class="fa fa-google-plus-square" aria-hidden="true"></i>
                        <span>GOOGLE+</span>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 connection-item">
                    <div class="col-xs-12 item">
                        <i class="fa fa-youtube-square" aria-hidden="true"></i>
                        <span>YOUTUBE</span>
                    </div>
                </div>
                <div class="col-md-2 col-sm-4 col-xs-6 connection-item">
                    <div class="col-xs-12 item">
                        <i class="fa fa-phone-square" aria-hidden="true"></i>
                        <span>ZALO</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="col-sm-6 col-xs-12 padding-top-bottom-20">
                <div class="footer-header"><i class="fa fa-home" aria-hidden="true"></i>&nbsp;&nbsp;Kết nối với chúng tôi</div>
                <div class="footer-content padding-top-5">
                    <div class="fb-page" data-href="https://www.facebook.com/thegioikhoedep/" data-tabs="timeline" data-width="340" data-height="210" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/thegioikhoedep/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/thegioikhoedep/">thegioikhoedep.com - HỆ THỐNG BÁN LẺ TP CHỨC NĂNG - MỸ PHẨM CHÍNH HÃNG</a></blockquote></div>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 padding-top-bottom-20">
                <div class="footer-header"><i class="fa fa-life-ring" aria-hidden="true"></i>&nbsp;&nbsp;Hỗ trợ</div>
                <div class="footer-content">
                    <ul>
                        <li>
                            <a href="gioi-thieu.aspx">Giới thiệu</a>
                        </li>
                        <li>
                            <a href="san-pham.aspx?danh-muc=tat-ca">Sản phẩm</a>
                        </li>
                        <li>
                            <a href="tin-tuc.aspx?type=tin-tuc">Tin tức</a>
                        </li>
                        <li>
                            <a href="tin-tuc.aspx?type=khuyen-mai">Khuyến mại</a>
                        </li>
                        <li>
                            <a href="tin-tuc.aspx?type=tuyen-dung">Tuyển dụng</a>
                        </li>
                        <li>
                            <a href="lien-he.aspx">Liên hệ</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3 col-xs-12 padding-top-bottom-20">
                <div class="footer-header"><i class="fa fa-bullhorn" aria-hidden="true"></i>&nbsp;&nbsp;Thông tin</div>
                <div class="footer-content">
                    <div class="col-xs-12">
                        Họ tên:
                        <input type="text" class="form-control input-md margin-top-5 margin-bottom-10">
                    </div>
                    <div class="col-xs-12">
                        Số điện thoại:
                        <input type="text" class="form-control input-md margin-top-5 margin-bottom-10">
                    </div>
                    <div class="col-xs-12">
                        <button type="button" class="btn btn-warning btn-md btn-block"><i class="fa fa-rss-square" aria-hidden="true"></i>&nbsp;&nbsp;Đăng ký nhận thông tin</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="col-xs-12 padding-top-bottom-20">
                <div class="col-md-6 col-sm-12 col-xs-12" style="font-size: 12px;">
                    <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" style="width: 40%; height: auto;"><br />
                    <b>Copyright 2013 © STELLA KINETICS LTD. All rights reserved</b><br />
                    Tầng 5, số 231 - 233 Lê Thánh Tôn, P. Bến Thành, Q.1, Tp Hồ Chí Minh<br />
                    Website hiện đang trong giai đoạn demo, đang đăng ký với Bộ Công Thương, không giao dịch thương mại điện tử
                </div>
            </div>
            <div class="col-xs-12 smacnew" style="font-size: 12px;">
                Website được phát triển bởi <b><a href="http://smacnew.com">SmacNew Co.,Ltd</a></b>
            </div>
        </div>
    </div>
</footer>
<!-- Script -->
<!-- <script type="text/javascript" src="scripts/jquery.min.js"></script>
<script type="text/javascript" src="scripts/jquery.smartmenus.js"></script>
<script type="text/javascript" src="plugins/bootstrap-3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="scripts/scripts.js"></script>
<script type="text/javascript" src="plugins/owlcarousel-2.2.1/owl.carousel.js"></script> -->
<script>
    $('.carousel').carousel({
        interval: 3000
    });

    $(document).ready(function () {
        var owl = $('.owl-carousel');
        owl.owlCarousel({
            items: 5,
            loop: true,
            margin: 10,
            autoplay: true,
            autoplayTimeout: 2000,
            autoplayHoverPause: false,
            responsiveClass: true,
            responsive: {
                0: {
                    items: 1,
                    nav: true
                },
                600: {
                    items: 3,
                    nav: false
                },
                1000: {
                    items: 5,
                    nav: true,
                    loop: false
                }
            }
        });
    })

    // SmartMenus init
    $(function () {
        $('#main-menu').smartmenus({
            subMenusSubOffsetX: 1,
            subMenusSubOffsetY: -8
        });
    });

    // SmartMenus mobile menu toggle button
    $(function () {
        var $mainMenuState = $('#main-menu-state');
        if ($mainMenuState.length) {
            // animate mobile menu
            $mainMenuState.change(function (e) {
                var $menu = $('#main-menu');
                if (this.checked) {
                    $menu.hide().slideDown(250, function () { $menu.css('display', ''); });
                } else {
                    $menu.show().slideUp(250, function () { $menu.css('display', ''); });
                }
            });
            // hide mobile menu beforeunload
            $(window).bind('beforeunload unload', function () {
                if ($mainMenuState[0].checked) {
                    $mainMenuState[0].click();
                }
            });
        }
    });
</script>
<script>
    // tell the embed parent frame the height of the content
    if (window.parent && window.parent.parent) {
        window.parent.parent.postMessage(["resultsFrame", {
            height: document.body.getBoundingClientRect().height,
            slug: "7k3wu7no"
        }], "*")
    }
</script>