<div id="fb-root"></div>
<script>
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=963514153780722";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<div class="row top-bar">
    <div class="container">
        <!--<a href="index.html">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 logo-img">
                <img src="images/logo.png" alt="Logo" />
            </div>
        </a>-->
        <div class="search-bar">
            <input type="text" class="form-control" /><button type="button" class="btn btn-danger"><i class="fa fa-search" aria-hidden="true"></i></button>
        </div>
        <div class="function-bar pull-right">
            <a href="#" class="item">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                &nbsp;&nbsp;<span>Giỏ hàng</span>
            </a>
            &nbsp;&nbsp;&nbsp;
            <a href="#" class="item">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                &nbsp;&nbsp;<span>Đăng ký | Đăng nhập</span>
            </a>
            &nbsp;&nbsp;&nbsp;
            <a href="#" class="item">
                <i class="fa fa-phone" aria-hidden="true"></i>
                &nbsp;&nbsp;<span>Hỗ trợ khách hàng</span>
            </a>
        </div>
    </div>
</div>
