<div class="row top-navbar" style="background-color: #ffffff;">
    <div class="container">
        <nav class="main-nav" role="navigation">

            <!-- Mobile menu toggle button (hamburger/x icon) -->
            <input id="main-menu-state" type="checkbox">
            <label class="main-menu-btn" for="main-menu-state">
                <span class="main-menu-btn-icon"></span> Toggle main menu visibility
            </label>

            <div class="nav-brand">
                <a href="index.html">
                    <div class="logo-img">
                        <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" alt="Logo" />
                    </div>
                </a>
            </div>

            <!-- Sample menu definition -->
            <ul id="main-menu" class="sm sm-blue" data-smartmenus-id="14907940667025815">
                <li class="has-mega-menu">
                    <a href="#" class="has-submenu header-text" id="sm-14907940667025815-1" aria-haspopup="true" aria-controls="sm-14907940667025815-2" aria-expanded="false"><span class="sub-arrow">+</span> <i class="fa fa-home" aria-hidden="true" style="font-size: 15px;"></i>&nbsp;&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="mega-menu sm-nowrap" id="sm-14907940667025815-2" role="group" aria-hidden="true" aria-labelledby="sm-14907940667025815-1" aria-expanded="false" style="width: auto; min-width: 10em; display: none; max-width: 20em; top: auto; left: 0px; margin-left: -366.188px; margin-top: 0px;">
                        <li>
                            <div class="column-1-4">
                                <h5 class="header-text">Thế giới làm đẹp</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Về chúng tôi</a></li>
                                    <li><a href="#">Câu chuyện của chúng tôi</a></li>
                                </ul>
                            </div>
                            <div class="column-1-4">
                                <h5 class="header-text">Gói quà tặng</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg'" />
                                </div>
                                <ul>
                                    <li><a href="#">Set 1</a></li>
                                    <li><a href="#">Set 2</a></li>
                                    <li><a href="#">Set 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-4">
                                <h5 class="header-text">Khuyễn mại mới nhất</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">KM 1</a></li>
                                    <li><a href="#">KM 2</a></li>
                                    <li><a href="#">KM 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-4">
                                <h5 class="header-text">Hỗ trợ</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Hỗ trợ khách hàng</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                    <li><a href="#">Chính sách bỏ sỉ</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul><span class="scroll-up" style="top: auto; left: 0px; margin-left: -366.188px; width: 927px; z-index: 3; margin-top: -59px; visibility: hidden; display: none;"><span class="scroll-up-arrow"></span></span><span class="scroll-down" style="display: none; top: auto; left: 0px; margin-left: -366.188px; width: 927px; z-index: 3; margin-top: 241px; visibility: hidden;"><span class="scroll-down-arrow"></span></span>
                </li>
                <li class="has-mega-menu">
                    <a href="#" class="has-submenu header-text" id="sm-14907940667025815-3" aria-haspopup="true" aria-controls="sm-14907940667025815-4" aria-expanded="false"><span class="sub-arrow">+</span>Mỹ phẩm&nbsp;&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="mega-menu" id="sm-14907940667025815-4" role="group" aria-hidden="true" aria-labelledby="sm-14907940667025815-3" aria-expanded="false">
                        <li>
                            <div class="column-1-5">
                                <h5 class="header-text">Trang điểm mặt</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-5">
                                <h5 class="header-text">Son môi</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-5">
                                <h5 class="header-text">Trang điểm mắt</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-5">
                                <h5 class="header-text">Nước hoa</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-5">
                                <h5 class="header-text">Makeup Tips</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Bài viết mới nhất 1</a></li>
                                    <li><a href="#">Bài viết mới nhất 2</a></li>
                                    <li><a href="#">Bài viết mới nhất 3</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="has-mega-menu">
                    <a href="#" class="has-submenu header-text" id="sm-14907940667025815-5" aria-haspopup="true" aria-controls="sm-14907940667025815-6" aria-expanded="false"><span class="sub-arrow">+</span>Chăm sóc tóc - body&nbsp;&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="mega-menu" id="sm-14907940667025815-6" role="group" aria-hidden="true" aria-labelledby="sm-14907940667025815-5" aria-expanded="false">
                        <li>
                            <div class="column-1-3">
                                <h5 class="header-text">Chăm sóc tóc</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-3">
                                <h5 class="header-text">Chăm sóc body</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-3">
                                <h5 class="header-text">Tips</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Bài viết mới nhất 1</a></li>
                                    <li><a href="#">Bài viết mới nhất 2</a></li>
                                    <li><a href="#">Bài viết mới nhất 3</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="has-mega-menu">
                    <a href="#" class="has-submenu header-text" id="sm-14907940667025815-7" aria-haspopup="true" aria-controls="sm-14907940667025815-8" aria-expanded="false"><span class="sub-arrow">+</span>Thực phẩm chức năng&nbsp;&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="mega-menu" id="sm-14907940667025815-8" role="group" aria-hidden="true" aria-labelledby="sm-14907940667025815-7" aria-expanded="false">
                        <li>
                            <div class="column-1-3">
                                <h5 class="header-text">Chăm sóc tóc</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-3">
                                <h5 class="header-text">Chăm sóc body</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Sản phẩm 1</a></li>
                                    <li><a href="#">Sản phẩm 2</a></li>
                                    <li><a href="#">Sản phẩm 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-3">
                                <h5 class="header-text">Tips</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Bài viết mới nhất 1</a></li>
                                    <li><a href="#">Bài viết mới nhất 2</a></li>
                                    <li><a href="#">Bài viết mới nhất 3</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>

                <li class="has-mega-menu">
                    <a href="#" class="has-submenu header-text" id="sm-14907940667025815-9" aria-haspopup="true" aria-controls="sm-14907940667025815-10" aria-expanded="false"><span class="sub-arrow">+</span>Blog&nbsp;&nbsp;<i class="fa fa-angle-down" aria-hidden="true"></i></a>
                    <ul class="mega-menu" id="sm-14907940667025815-10" role="group" aria-hidden="true" aria-labelledby="sm-14907940667025815-9" aria-expanded="false">
                        <li>
                            <div class="column-1-3">
                                <h5 class="header-text">Đánh giá</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Bài viết mới nhất 1</a></li>
                                    <li><a href="#">Bài viết mới nhất 2</a></li>
                                    <li><a href="#">Bài viết mới nhất 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-3">
                                <h5 class="header-text">Trang điểm</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Bài viết mới nhất 1</a></li>
                                    <li><a href="#">Bài viết mới nhất 2</a></li>
                                    <li><a href="#">Bài viết mới nhất 3</a></li>
                                </ul>
                            </div>
                            <div class="column-1-3">
                                <h5 class="header-text">Chăm sóc sức khỏe</h5>
                                <div class="mega-menu-sample-image">
                                    <img src="images/adiva.jpg" />
                                </div>
                                <ul>
                                    <li><a href="#">Bài viết mới nhất 1</a></li>
                                    <li><a href="#">Bài viết mới nhất 2</a></li>
                                    <li><a href="#">Bài viết mới nhất 3</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>