<div class="row">
    <div class="container chi-tiet-san-pham margin-top-40">
        <div class="col-sm-6 col-xs-12 sp-image">
            <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-1.png'); ?>" />
        </div>
        <div class="col-sm-6 col-xs-12 padding-left-right-15-mobile">
            <div class="col-xs-12 ten-sp">
                Bộ 2 Thực Phẩm Bảo Vệ Sức Khỏe Nghệ Viên ADIVA (30 viên/Hộp) + Quà Tặng: 1 Sữa Rửa Mặt Trắng Sáng Da iRENEW Brightening Facial Cleanser (100ml)
            </div>
            <div class="col-xs-12 gia-cu">
                <b>Giá cũ:</b>&nbsp;<span>120.000 đ</span>
            </div>
            <div class="col-xs-12 gia-moi">
                <b>Giá mới:</b>&nbsp;<span>90.000 đ</span>
            </div>
            <div class="col-xs-12 ma-sp">
                <b>Mã sản phẩm:</b>&nbsp;<span>SP0123456789</span>
            </div>
            <div class="col-xs-12 thuong-hieu-sp">
                <b>Thương hiệu:</b>&nbsp;<span>ABC XYZ</span>
            </div>
            <div class="col-xs-12">
                <div class="col-xs-6 btn-group">
                    <button type="button" class="btn btn-success btn-block btn-muangay">Mua ngay</button>
                </div>
                <div class="col-xs-6 btn-group">
                    <a href="gio-hang.html" class="btn btn-danger btn-block btn-muangay">Thêm vào giỏ hàng</a>
                </div>
            </div>
            <div class="col-xs-12 ghi-chu">
                <b><i class="fa fa-truck" aria-hidden="true"></i>&nbsp;&nbsp;Miễn phí giao hàng</b>
            </div>
            <div class="col-xs-12 ghi-chu">
                <b><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;Ship COD - Trả tiền khi nhận hàng</b>
            </div>
            <div class="col-xs-12 ghi-chu">
                <b><i class="fa fa-refresh" aria-hidden="true"></i>&nbsp;&nbsp;Đổi trả trong vòng 5 ngày</b>
            </div>
            <div class="col-xs-12 noity-sp">
                <div class="alert alert-danger text-center">
                    <strong>HOÀN TIỀN 100%</strong> nếu không phải hàng chính hãng!
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="container">
        <div class="col-xs-12 thong-tin-san-pham">
            <div class="col-xs-12 prod-group-title">
                <div class="prod-group-name pull-left padding-left-right-15-mobile">
                    THÔNG TIN SẢN PHẨM
                </div>
            </div>
            <div class="col-xs-12 padding-left-right-15-mobile">
                <br /><br />Bộ 2 Thực Phẩm Bảo Vệ Sức Khỏe Nghệ Viên ADIVA (30 viên/Hộp) + Quà Tặng: 1 Hộp Bella Luce Nourishing Cell Face Mask (30g x 10 miếng)

                <br /><br />Thực Phẩm Bảo Vệ Sức Khỏe Nghệ Viên Adiva (30 viên/Hộp)
                <br /><br />Thực phẩm bảo vệ sức khỏe Nghệ viên ADIVA được sản xuất và nhập khẩu 100% tại Đức, ứng dụng sản xuất công nghệ mới nhất Nano-micelles, vỏ nang Gelatin chiết xuất từ thực vật, khắc phục được nhược điểm hấp thụ kém của các sản phẩm nghệ thông thường. Một viên tinh chất nghệ ADIVA chứa 720 mg Novasol Curcumin, tương đương 5,5Kg nghệ tươi. Uống một viên mỗi ngày sẽ đạt hiệu quả hỗ trợ điều trị viêm loét dạ dày, viêm gan do bia rượu, ngăn ngừa hình thành các tế bào ung thư và bảo vệ sức khỏe tối ưu.

                <br /><br />Nghệ Viên Adiva

                <br /><br />Curcumin là gì?
                <br /><br />Curcumin là hoạt chất quan trọng nhất trong củ nghệ, chỉ chiếm khoảng 3 – 5% khối lượng. Curcumin đã được chứng minh hiệu quả và an toàn trong việc hỗ trợ điều trị và ngăn ngừa các bệnh mạn tính, ung thư như: viêm loét dạ dày, tá tràng, tiểu đường, viêm gan, phòng ngừa hình thành các tế bào ung thư mà không có bất kỳ tác dụng phụ nào, thậm chí với liều lên đến 8.000mg mỗi ngày… Tuy nhiên, Curcumin thông thường không tan được trong nước (độ tan 0,001%) nên tính khả dụng rất thấp.

                <br /><br />Tại Hoa Kỳ, Curcumin đã được cấp " Chứng nhận An toàn "(GRAS) theo FDA.

                <br /><br />Ứng dụng Công nghệ Nano – micelles
                <br /><br />Thực Phẩm Bảo Vệ Sức Khỏe Nghệ Viên ADIVA được sản xuất theo công nghệ tiên Nano-micelles, giúp tạo ra những hạt phân tử Curcumin với kích thước siêu nhỏ chỉ 30 nm và kết hợp thêm 1 nhóm phân tử micells có đầu ưa nước, có khả năng hấp thu hoàn toàn vào cơ thể chỉ sau 1 giờ 10 phút,  phát huy sinh khả dụng gấp 185 lần so với tinh nghệ thông thường.

                <br /><br />6 Công dụng tối ưu:
                <br />Hỗ trợ điều trị và ngăn ngừa bệnh viêm loét dạ dày.
                <br />Hỗ trợ điều trị và ngăn ngừa nhiễm độc gan, viêm gan do bia rượu gây ra.
                <br />Giảm nguy cơ bệnh tiểu đường.
                <br />Giảm mỡ trong máu.
                <br />Giảm rủi ro hình thành các tế bào ung thư.
                <br />Bảo vệ hệ thần kinh
                <br />Nghệ Viên Adiva

                <br /><br />Nghệ viên Adiva

                <br /><br />Ưu điểm vượt trội nghệ viên Adiva:
                <br /><br />Sản xuất và nhập khẩu 100% tại Đức

                <br /><br />Ứng dụng Công nghệ Nano – Micelles phát huy sinh khả dụng gấp 185 lần viên nghệ thông thường.

                <br /><br />Vỏ viên nang bằng gelatin thực vật, dễ hấp thụ, tan hoàn toàn chỉ sau 7 phút, an toàn cho sức khỏe người tiêu dùng.

                <br /><br />1 viên tinh chất nghệ tương đương 5,5Kg Nghệ tươi

                <br /><br />Đối Tượng Sử Dụng:
                <br />- Nam, Nữ 18 tuổi trở lên.

                <br />- Người bị viêm loét dạ dày, tá tràng, viêm đại tràng.

                <br />- Người bị viêm gan mạn tính, nhiễm độc gan, viêm gan do bia rượu.

                <br />- Người đang trong quá trình phục hồi sau mổ, sau chấn thương.

                <br />- Người bị viêm khớp cấp và mạn tính, đau nhức khớp.

                <br />- Người trong và sau khi điều trị ung thư.

                <br />- Người muốn duy trì sức khỏe & bảo vệ thần kinh.

                <br />- Phụ nữ sau sinh, người đang phục hồi sức khỏe.

                <br /><br />*Hiệu quả của sản phẩm còn tùy thuộc vào cơ địa và thể trạng của mỗi người

                <br /><br />Quà tặng: Sữa Rửa Mặt Trắng Sáng Da iRENEW Brightening Facial Cleanser (100ml)

                <br /><br />Chứa tế bào gốc thực vật chiết xuất từ mầm đậu xanh, tinh dầu chiết xuất từ quả cam và các loại quả giàu vitamin A, E và C, Sữa Rửa Mặt Làm Trắng Sáng Da iRENEW Brightening Facial Cleanser là giải pháp tối ưu để làm sạch và phục hồi làn da bạn:

                <br /><br />Làm sạch bụi bẩn, bã nhờn, giúp da sạch mịn màng.
                <br />Nhẹ nhàng loại bỏ vi khuẩn và tế bào chết, cho làn da mềm mượt, sáng khỏe.
                <br />Giúp se khít lỗ chân lông, ngăn ngừa sự hình thành của mụn, đặc biệt là mụn đầu đen.
                <br />Bổ sung các dưỡng chất, tăng cường hệ thống miễn dịch tự nhiên cho da.
                <br />*Hiệu quả của sản phẩm còn tùy thuộc vào cơ địa và thể trạng của mỗi người

                <br /><br />Sữa Rửa Mặt Trắng Sáng Da iRENEW

                <br /><br />Xem thêm review sản phẩm tại đây

                <br /><br />Tế bào gốc thực vật là loại tế bào có khả năng biệt hóa thành nhiều loại tế bào có các chức năng khác nhau, hiệu quả trong việc loại bỏ các tế bào sừng hóa, các mảng sắc tố da sậm màu, ức chế hoạt động của melanin.

                <br /><br />Sử dụng Sữa Rửa Mặt Làm Trắng Sáng Da iRENEW Brightening Facial Cleanser hàng ngày kết hợp với Tinh Chất Làm Tươi Trẻ Và Trắng Sáng Làn Da iRENEW Double Vitamin C Brightening Serum sẽ nhanh chóng mang đến cho bạn một làn da sáng khỏe, mịn mượt và tràn đầy năng lượng.

                <br /><br />Sản phẩm được sản xuất theo tiêu chuẩn nghiêm ngặt của FDA (Cục quản lý thực phẩm & Dược phẩm Hoa Kỳ), không chứa paraben, không gây kích ứng da.

                <br /><br />Thành phần: Deionized Water, Water (and) Sodium Lauroyl Methyl Isethionate (and) Cocamidopropyl Betaine (and) Sodium  Cocoyl Isethionate (and) Sodium Methyl Oleoyl Taurate, PEG-7 Glyceryl Cocoate, Glycol Distearate (and) Laureth-4 (and) Cocamidopropyl Betaine, Acrylates Copolymer, Citrus Aurantium Dulcis (Sweet Orange) Fruit Extract, Polyquaternium-7, Vigna Radiata (Phaseolus Radiatus) Meristem Cell Culture Extract (Plant Stem C), Water (and) Butylene Glycol (and) Hydrogenated Lecithin (and) Sodium Oleate (and) Oligopeptide-68 (and) Disodium EDTA (B-White), Phenoxyethanol (and) Ethyhexyglyerin, Fragrance

                <br /><br />Sữa Rửa Mặt Trắng Sáng Da iRENEW

                <br /><br />HƯỚNG DẪN SỬ DỤNG

                <br /><br />Nên sử dụng Nghệ viên ADIVA khi bụng đói, 1 viên * 1 lần/ngày.

                <br /><br />BẢO QUẢN: Nơi khô mát, tránh ánh sáng trực tiếp.

                <br /><br />SẢN XUÂT TẠI: AQUANOVA AG Co., Ltd. Địa chỉ: Birkenweg 8 – 10, 64295 Darmstadt, Gemany.

                <br /><br />ĐÓNG GÓI BỞI: CÔNG TY TNHH TMDV TRẦN TOÀN PHÁT. Địa chỉ: 25-27-29 Đường D5, P. 25, Q. Bình Thạnh, TP.HCM

                <br /><br />NHẬP KHẨU VÀ PHÂN PHỐI BỞI:

                <br /><br />CÔNG TY TNHH TMDV TRẦN TOÀN PHÁT. Địa chỉ:  25-27-29 Đường D5, P. 25, Q. Bình Thạnh, TP.HCM

                <br /><br />Sữa Rửa Mặt Trắng Sáng Da iRENEW Brightening Facial Cleanser (100ml)

                <br /><br />Sau khi làm ướt da mặt bằng nước ấm, nhấn nhẹ chai từ 1 – 2 lần cho gel rửa mặt ra lòng bàn tay, thêm một ít nước để tạo thành bọt mịn và massage nhẹ nhàng lên da theo chiều từ dưới lên trên trong khoảng 30 giây. Sau đó rửa sạch bằng nước ấm và lau khô bằng khăn mềm.

                <br /><br />Sử dụng 2 lần/ngày vào mỗi buổi sáng và tối

                <br /><br />Lưu ý: Tránh để sản phẩm tiếp xúc với mắt. Trong trường hợp sản phẩm dính vào mắt, hãy rửa sạch bằng nước. Bảo quản nơi khô ráo, thoáng mát, tránh xa tầm tay trẻ em.
            </div>
        </div>
    </div>
</div>