<div class="row top-after">
    <div class="container">
        <div class="col-xs-12 gio-hang padding-left-right-15-mobile">
            <div class="col-xs-12 gio-hang-title">
                <i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;THÔNG TIN KHÁCH HÀNG
            </div>
            <div class="col-xs-12 thong-tin-khach-hang padding-left-right-15-mobile">
                <div class="col-sm-2 col-xs-12">
                </div>
                <div class="col-sm-4 col-xs-12 padding-right-20-desktop">
                    <div class="col-xs-12">
                        Họ tên: <span class="required">*</span>
                        <input type="text" class="form-control margin-top-5 margin-bottom-10">
                    </div>
                    <div class="col-xs-12">
                        Số điện thoại: <span class="required">*</span>
                        <input type="text" class="form-control margin-top-5 margin-bottom-10">
                    </div>
                    <div class="col-xs-12">
                        Email:
                        <input type="text" class="form-control margin-top-5 margin-bottom-10">
                    </div>
                </div>
                <div class="col-sm-4 col-xs-12 padding-left-20-desktop">
                    <div class="col-xs-12">
                        Tỉnh/Thành phố: <span class="required">*</span>
                        <select class="form-control margin-top-5 margin-bottom-10">
                            <option value="1">Hà Nội</option>
                            <option value="2">Hải Phòng</option>
                            <option value="3">Huế</option>
                            <option value="4">Đà Nẵng</option>
                            <option value="5">Sài Gòn</option>
                        </select>
                    </div>
                    <div class="col-xs-12">
                        Quận/Huyện: <span class="required">*</span>
                        <select class="form-control margin-top-5 margin-bottom-10">
                            <option value="1">Hải Châu</option>
                            <option value="2">Sơn Trà</option>
                            <option value="3">Thanh Khê</option>
                            <option value="4">Hòa Xuân</option>
                            <option value="5">Hòa Quý</option>
                        </select>
                    </div>
                    <div class="col-xs-12">
                        Địa chỉ:
                        <input type="text" class="form-control margin-top-5 margin-bottom-10">
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12 ">
                <div class="col-xs-12 gio-hang-infor ">
                    <div class="col-sm-4 col-xs-6">
                        Tổng giá trị:
                    </div>
                    <div class="col-sm-4 col-xs-6 tong-gia-tri">
                        180.000 đ
                    </div>
                </div>
                <div class="col-xs-12 gio-hang-infor ">
                    <div class="col-sm-4 col-xs-6">
                        Phí vận chuyển:
                    </div>
                    <div class="col-sm-4 col-xs-6" style="font-size: 14px;">
                        30.000 đ
                    </div>
                </div>
                <div class="col-xs-12 gio-hang-infor ">
                    <div class="col-sm-4 col-xs-6">
                        Tổng giá trị đơn hàng:
                    </div>
                    <div class="col-sm-4 col-xs-6 tong-don-hang">
                        180.000 đ
                    </div>
                </div>
                <div class="col-xs-12 gio-hang-infor">
                    <div class="col-sm-4 col-xs-12">
                        <a href="/user/MyCart" class="btn btn-default btn-xs btn-block margin-top-10"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;Quay lại giỏ hàng</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12">
                <div class="col-sm-6 col-xs-12 pull-right margin-top-5">
                    <a href="/user/MyCart/Purchase" class="btn btn-danger btn-lg btn-block">THANH TOÁN&nbsp;&nbsp;<i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </div>
</div>