<div class="row top-after">
    <div class="container">
        <div class="col-xs-12 gio-hang padding-left-right-15-mobile">
            <div class="col-xs-12 gio-hang-title">
                <i class="fa fa-exchange" aria-hidden="true"></i>&nbsp;&nbsp;THANH TOÁN
            </div>
            <div class="col-xs-12 thanh-toan">
                <div class="col-sm-3 col-xs-12 padding-right-20-desktop  margin-top-10">
                    <span class="thanh-toan-title">Phương thức thanh toán</span> <span class="required">*</span>
                    <br />
                    <div class="radio">
                        <label><input type="radio" name="optradio" checked>Thanh toán khi giao hàng</label>
                    </div>
                    <div class="radio">
                        <label><input type="radio" name="optradio">Chuyển khoản ngân hàng</label>
                    </div>
                    <br/>
                    <span class="thanh-toan-title">Địa điểm giao hàng</span>
                    <br />
                    <label class="margin-top-10" style="font-weight: 300;">abc xyz</label>
                </div>
                <div class="col-sm-9 col-xs-12 margin-top-10">
                    <span class="thanh-toan-title">Thông tin đơn hàng</span>
                    <br />
                    <div class="col-xs-12 gio-hang-list" style="padding-top: 10px;">
                        <div class="col-xs-12 gio-hang-header">
                            <div class="col-sm-6 col-xs-4 text-left">
                                SẢN PHẨM
                            </div>
                            <div class="col-sm-2 col-xs-12">
                                ĐƠN GIÁ
                            </div>
                            <div class="col-sm-2 col-xs-12">
                                SỐ LƯỢNG
                            </div>
                            <div class="col-sm-2 col-xs-12 thanh-tien">
                                THÀNH TIỀN
                            </div>
                        </div>

                        <?php for($i = 0; $i < 2; $i++) { ?>
                            <div class="col-xs-12 gio-hang-item">
                                <div class="col-sm-2 col-xs-3 thumb">
                                    <img src="<?php echo $block->getViewFileUrl('images/prods/img-prod-' . ($i % 3) . '.png')?>" />
                                </div>
                                <div class="col-sm-4 col-xs-9">
                                    <div class="col-xs-12 title">
                                        Bộ Chăm Sóc Cơ Thể Karmarts + Qùa tặng: Gel Tẩy Tế Bào Chết Sữa Chua Dâu Cathy Doll So Happy Berry Yogurt Peeling Gel (60ml) & Xà Phòng Thảo Dược Dứa & AHA Cathy Doll Reunrom Herbal Soap Pineapple & AHA (55g)
                                    </div>
                                </div>
                                <div class="col-sm-2 col-xs-4 don-gia">
                                    <span class="mobile-mode">ĐƠN GIÁ</span><br />
                                    90.000 đ
                                </div>
                                <div class="col-sm-2 col-xs-4 so-luong">
                                    <span class="mobile-mode">SỐ LƯỢNG</span><br />
                                    1
                                </div>
                                <div class="col-sm-2 col-xs-4 thanh-tien">
                                    <span class="mobile-mode">THÀNH TIỀN</span><br />
                                    90.000 đ
                                </div>
                            </div>
                        <?php } ?>

                    </div>
                    <div class="col-xs-12">
                        <div class="col-xs-12 gio-hang-infor text-right ">
                            <div class="col-sm-3 col-xs-6 tong-gia-tri pull-right">
                                180.000 đ
                            </div>
                            <div class="col-sm-4 col-xs-6 pull-right">
                                Tổng giá trị:
                            </div>
                        </div>
                        <div class="col-xs-12 gio-hang-infor  text-right ">
                            <div class="col-sm-3 col-xs-6 pull-right" style="font-size: 14px;">
                                30.000 đ
                            </div>
                            <div class="col-sm-4 col-xs-6 pull-right">
                                Phí vận chuyển:
                            </div>
                        </div>
                        <div class="col-xs-12 gio-hang-infor text-right  ">
                            <div class="col-sm-3 col-xs-6 tong-don-hang pull-right">
                                180.000 đ
                            </div>
                            <div class="col-sm-4 col-xs-6 pull-right">
                                Tổng giá trị đơn hàng:
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 agree-thanh-toan">
                        <div class="col-xs-12">
                            <label class="checkbox-inline"><input type="checkbox" value="">&nbsp;Tôi đồng ý với</label> Điểu khoản mua hàng.
                        </div>
                        <div class="col-xs-12 margin-top-10">
                            Ghi chú:
                            <textarea class="form-control margin-top-5" style="width: 100%" rows="5" id="comment"></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12 pull-right">
                <div class="col-sm-6 col-xs-12 pull-right margin-top-5">
                    <button type="button" class="btn btn-danger btn-lg btn-block">HOÀN TẤT ĐẶT HÀNG&nbsp;&nbsp;<i class="fa fa-check-circle-o" aria-hidden="true"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>